spring:
  application:
    name: ${APPLICATION_NAME:detection-be}
  data:
    redis:
      port: ${REDIS_PORT:6379}
      host: ${REDIS_HOST:115.73.218.193}
      database: 0


server:
  port: ${SERVER_PORT:8081}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

logging:
  level:
    org.springframework.web.socket=DEBUG:
    org.springframework.web=DEBUG:

app:
  jwt-secret: ${JWT_SECRET:123456}
  jwt-expiration-milliseconds: ${JWT_EXPIRATION:86400000}