spring:
  application:
    name: detection-be

server:
  port: ${SERVER_PORT:8081}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

logging:
  level:
    org.springframework.web.socket=DEBUG:
    org.springframework.web=DEBUG:

