on:
  push:
    branches:
      - deploy/develop
  workflow_dispatch:
  
jobs:
  run_pull:
    name: run pull
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    
    - name: Add SSH Key
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Add remote server to known_hosts
      run: |
        ssh-keyscan user@remote_server >> ~/.ssh/known_hosts    # Replace user@remote_server
    
    - name: Connect, Pull, and Build
      run: |
        sshpass -p "${{ secrets.SSH_PASS }}" ssh -o StrictHostKeyChecking=no admin@pog.threemusketeer.click << EOF
          set -e
          cd /home/admin/Documents/roomify/roomify-media-be
          git stash
          git pull origin deploy/develop
          cd /home/admin/Documents/roomify && docker compose up --build
        EOF
